### ISSUE TITLE
IDR: missing knowldgebases

### ISSUE THREAD

**Issue by dartraiden** [indetectables-net/toolkit#10]
https://github.com/crypto2011/IDR#readme

```
!!! Knowledge bases for various Delphi versions can be found at: https://drive.google.com/drive/folders/1IBsO1_O9xGHkPPV9Pnqkq2uoFmuak5C7?usp=sharing
```

They should be placed next to idr.exe

**Comment by xchwarze** [comment]
I can't add them all because of the size, but I added a few anyway.
In any case, the updater has a flag to mark the tools to be merged with the local copy. Thanks to this you could download them all in your installation and the updater would keep them for you.
In the version that I am testing to launch, several tools are already configured by default with the merge parameter.
