### ISSUE TITLE
"Zombie" HxD fails to launch when Toolkit installed under Program Files

### ISSUE THREAD

**Issue by l3fdb33f** [indetectables-net/toolkit#11]
Whenever I launch HxD from shortcut or the binary itself I get this error and it doesn't launch. Plus, it keeps re-launching until you kill 2 sets of process trees almost at the same time.
![Screen Shot 2023-01-05 at 1 00 42 AM](https://user-images.githubusercontent.com/25807782/210712367-627aee9b-d432-4862-ad20-1edb3df3c338.png)

 I saw a related article about this issue and it seems to have something to do with the install directory: https://forum.mh-nexus.de/viewtopic.php?t=1160
 This issue didn't happen when I uninstalled and reinstalled in a user-specific directory but repeated itself when installing under Program Files.

**Comment by xchwarze** [comment]
That's because the program creates files or folders in the directory where it runs.
Windows to write to that path always needs the process to be running elevated.
I guess the solution would be to recreate those files in the bat that updates the program so that it doesn't fail in this case.
I have it installed in another partition so the program does not fail me.

**Comment by xchwarze** [comment]
Fixed in next build
